module.exports =[
  {
    name: 'Baby Yoda',
    img: 'baby-yoda.png',
    year: 2019,
    category: '',
  },
  {
    name: 'Me and the Boys',
    img: 'me-and-the-boys.png',
    year: 2019,
    category: '',
  },
  {
    name: 'Stonks',
    img: 'stonks.png',
    year: 2019,
    category: '',
  },
  {
    name: 'Woman Yelling at a Cat',
    img: 'woman-yelling-at-a-cat.jpg',
    year: 2019,
    category: '',
  },
  {
    name: 'Joker stairs',
    img: 'joker-stairs.jpg',
    year: 2019,
    category: '',
  },
  {
    name: 'Boomer vs Zoomer',
    img: 'boomer-vs-zoomer.jpg',
    year: 2019,
    category: '',
  },
  {
    name: 'American Chopper Argument',
    img: 'american-chopper-argument.jpg',
    year: 2018,
    category: '',
  },
  {
    name: 'Bongo Cat',
    img: 'bongo-cat.jpg',
    year: 2018,
    category: '',
  },
  {
    name: 'Bowsette',
    img: 'bowsette.jpg',
    year: 2018,
    category: '',
  },
  {
    name: 'Is This a Pigeon?',
    img: 'is-this-a-pidgeon.jpg',
    year: 2018,
    category: '',
  },
  {
    name: 'Kongchetumare',
    img: 'kongchetumare.jpg',
    year: 2018,
    category: '',
  },
  {
    name: 'Moth Lamp',
    img: 'moth-lamp.jpg',
    year: 2018,
    category: '',
  },
  {
    name: 'Steamed Hams / Hamburguejas al vapor',
    img: 'steamed-hams.jpg',
    year: 2018,
    category: 'simpsons',
  },
  {
    name: 'Surprised Pikachu',
    img: 'surprised-pikachu.jpg',
    year: 2018,
    category: '',
  },
  {
    name: 'Burns pero la concha de tu madre (blank)',
    img: 'burns-pero-la-concha-de-tu-madre-blank.jpg',
    year: 2019,
    category: 'simpsons',
  },
  {
    name: 'Burns pero la concha de tu madre',
    img: 'burns-pero-la-concha-de-tu-madre.jpg',
    year: 2019,
    category: 'simpsons',
  },
  {
    name: 'Rafa: Estoy feliz y enojado',
    img: 'rafa-estoy-feliz-y-enojado.jpg',
    category: 'simpsons',
  },
  {
    name: 'Homero: Poder político',
    img: 'homero-poder-politico.jpg',
    category: 'simpsons',
  },
  {
    name: 'Usted no aprende verdad',
    img: 'usted-no-aprende-verdad.jpg',
    category: 'simpsons',
  },
  {
    name: 'Profesor Cocoon: Yo diría que sí',
    img: 'yo-diria-que-si.jpg',
    category: 'simpsons',
  },
  {
    name: 'Skinner: no hay cuerpos',
    img: 'skinner-no-hay-cuerpos.jpg',
    category: 'simpsons',
  },
  {
    name: 'Todo marcha bien Milhouse',
    img: 'todo-marcha-bien-milhouse.jpg',
    category: 'simpsons',
  },
  {
    name: 'Lisa café',
    img: 'lisa-cafe.jpg',
    category: 'simpsons',
  },
  {
    name: 'Lester',
    img: 'lester.jpg',
    category: 'simpsons',
  },
];
