module.exports =[
  {
    name: 'Baby Yoda',
    img: 'baby-yoda.png',
    editable: true,
    year: 2019,
    category: '',
  },
  {
    name: 'Me and the Boys',
    img: 'me-and-the-boys.png',
    editable: true,
    year: 2019,
    category: '',
  },
  {
    name: 'Stonks',
    img: 'stonks.png',
    editable: true,
    year: 2019,
    category: '',
  },
  {
    name: 'Woman Yelling at a Cat',
    img: 'woman-yelling-at-a-cat.jpg',
    editable: true,
    year: 2019,
    category: '',
  },
  {
    name: 'Joker stairs',
    img: 'joker-stairs.jpg',
    editable: true,
    year: 2019,
    category: '',
  },
  {
    name: 'Boomer vs Zoomer',
    img: 'boomer-vs-zoomer.jpg',
    editable: true,
    year: 2019,
    category: '',
  },
  {
    name: 'American Chopper Argument',
    img: 'american-chopper-argument.jpg',
    editable: true,
    year: 2018,
    category: '',
  },
  {
    name: 'Bongo Cat',
    img: 'bongo-cat.jpg',
    editable: true,
    year: 2018,
    category: '',
  },
  {
    name: 'Bowsette',
    img: 'bowsette.jpg',
    editable: true,
    year: 2018,
    category: '',
  },
  {
    name: 'Is This a Pigeon?',
    img: 'is-this-a-pidgeon.jpg',
    editable: true,
    year: 2018,
    category: '',
  },
  {
    name: 'Kongchetumare',
    img: 'kongchetumare.jpg',
    editable: true,
    year: 2018,
    category: '',
  },
  {
    name: 'Moth Lamp',
    img: 'moth-lamp.jpg',
    editable: true,
    year: 2018,
    category: '',
  },
  {
    name: 'Steamed Hams / Hamburguejas al vapor',
    img: 'steamed-hams.jpg',
    editable: true,
    year: 2018,
    category: 'simpsons',
  },
  {
    name: 'Surprised Pikachu',
    img: 'surprised-pikachu.jpg',
    editable: true,
    year: 2018,
    category: '',
  },
  {
    name: 'Burns pero la concha de tu madre (blank)',
    img: 'burns-pero-la-concha-de-tu-madre-blank.jpg',
    editable: true,
    year: 2019,
    category: 'simpsons',
  },
  {
    name: 'Burns pero la concha de tu madre',
    img: 'burns-pero-la-concha-de-tu-madre.jpg',
    editable: true,
    year: 2019,
    category: 'simpsons',
  },
  {
    name: 'Rafa: Estoy feliz y enojado',
    img: 'rafa-estoy-feliz-y-enojado.jpg',
    editable: true,
    category: 'simpsons',
  },
  {
    name: 'Homero: Poder político',
    img: 'homero-poder-politico.jpg',
    editable: true,
    category: 'simpsons',
  },
  {
    name: 'Usted no aprende verdad',
    img: 'usted-no-aprende-verdad.jpg',
    editable: true,
    category: 'simpsons',
  },
  {
    name: 'Profesor Cocoon: Yo diría que sí',
    img: 'yo-diria-que-si.jpg',
    editable: true,
    category: 'simpsons',
  },
  {
    name: 'Skinner: no hay cuerpos',
    img: 'skinner-no-hay-cuerpos.jpg',
    editable: true,
    category: 'simpsons',
  },
  {
    name: 'Todo marcha bien Milhouse',
    img: 'todo-marcha-bien-milhouse.jpg',
    editable: true,
    category: 'simpsons',
  },
  {
    name: 'Lisa café',
    img: 'lisa-cafe.jpg',
    editable: true,
    category: 'simpsons',
  },
  {
    name: 'Lester',
    img: 'lester.jpg',
    editable: true,
    category: 'simpsons',
  },
  {
    name: 'Spider-Man pointing at Spider-Man',
    img: 'spiderman-spiderman.jpg',
    editable: true,
    category: 'spiderman',
  },
  {
    name: 'George Harrison en los Simpson: esto ya se ha visto',
    img: 'esto-ya-se-ha-visto.jpg',
    editable: true,
    category: 'simpsons',
  },
  {
    name: 'Si ya saben como me pongo para qué me invitan',
    img: 'si-ya-saben-como-me-pongo.jpg',
    editable: true,
    category: '',
  },
  {
    name: 'Conceited reaction',
    img: 'conceited-reaction.gif',
    editable: false,
    category: '',
  },
  {
    name: 'El Diablo',
    img: 'el-diablo.gif',
    editable: false,
    category: '',
  },
  {
    name: '¿Por qué eres así?',
    img: 'por-que-eres-asi.jpg',
    editable: true,
    category: '',
  },
  {
    name: '¿Por qué eres así?',
    img: 'wey-ya.jpg',
    editable: true,
    category: '',
  },
  {
    name: 'Roll Safe',
    img: 'roll-safe.jpg',
    editable: true,
    category: '',
  },
  {
    name: 'Just right',
    img: 'just-right.jpg',
    editable: true,
    category: '',
  },
  {
    name: 'White guy blinking',
    img: 'white-guy-blinking.gif',
    editable: false,
    category: '',
  },
  {
    name: 'Me explaining to my mom',
    img: 'me-explaining-to-my-mom.jpg',
    editable: true,
    category: '',
  },
  {
    name: 'Amargo y retruco animé',
    img: 'amargo-y-retruco-anime.jpg',
    editable: true,
    category: 'argentina argentinos',
  },
  {
    name: 'Gay Jesus enters',
    img: 'gay-jesus-enters.gif',
    editable: false,
    category: '',
  },
];
